name: ci

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [dev, prod]
    steps:
      - uses: actions/checkout@v7
      - uses: hashicorp/setup-terraform@v3
      - run: terraform fmt -check -recursive
      - name: init (không backend) + validate
        working-directory: envs/${{ matrix.env }}
        run: |
          terraform init -backend=false -input=false
          terraform validate

  trivy-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Trivy IaC scan (misconfiguration)
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: config
          scan-ref: .
          severity: HIGH,CRITICAL
          exit-code: '1'
